### PR TITLE
FIX missing jstz library loading

### PR DESCRIPTION
**Pull request by hregis**

### CODE REVIEW

**Comment by eldy** [comment]
The library has been replaced by the native intl library (available in all browsers).
Which version and subversion of Dolibarr do you use ?

**Comment by hregis** [comment]
@eldy maybe add a check when v19 is used ? the native intl library is used in v20

**Comment by eldy** [comment]
> @eldy maybe add a check when v19 is used ? the native intl library is used in v20

Ok, i understand now.
Yes, can you add a check 
```
if ((float) DOL_VERSION <= 19) then keep the include of lib
else do not include it (does not exist anymore in v20).
```

**Comment by hregis** [comment]
@eldy it's ok, thanks

**Pull request merged**
